import time
import battery_monitor

device = battery_monitor.Device()

while True:
    voltage = device.readVoltage()
    current = device.readCurrent()
    power = device.readPower()
    temperature = device.readTemperature()
    humidity = device.readHumidity()

    # print(
    #     "Current: %.2f mA Voltage: %.2f V Power:%.2f mW\nTemperature: %0.1f C Humidity: %0.1f %%"
    #     % (voltage, current, power, temperature, humidity)
    # )

    print("set to 45")
    device.setVoltage(45)
    time.sleep(5)
    print("set to 46")
    device.setVoltage(46)
    time.sleep(5)
    print("set to 47")
    device.setVoltage(47)
    time.sleep(5)
    print("set to 48")
    device.setVoltage(48)
    time.sleep(5)
    print("set to 49")
    device.setVoltage(49)
    time.sleep(5)
    print("set to 50")
    device.setVoltage(50)
    time.sleep(5)
    print("set to 51")
    device.setVoltage(51)
    time.sleep(5)
    print("set to 52")
    device.setVoltage(52)
    time.sleep(5)
    print("set to 53")
    device.setVoltage(53)
    time.sleep(5)
    print("set to 54")
    device.setVoltage(54)
    time.sleep(5)
    print("set to 55")
    device.setVoltage(55)
    time.sleep(5)
    print("set to 56")
    device.setVoltage(56)
    time.sleep(5)
    print("set to 57")
    device.setVoltage(57)
    time.sleep(5)